### ISSUE TITLE
Stacks don't work with create bulk blasting

### ISSUE THREAD

**Issue by gggrafton** [frank89722/Staaaaaaaaaaaack#10]
When merged stacks are dropping in front of a bulk blaster it cooks the whole stacks however it does not give back the same amount when cooked

After some testing it seems to lose around 40-50% of the item stacks

**Comment by frank89722** [comment]
I am unable to replicate the issue you are experiencing. Could you please provide more details on how it occurred?

https://github.com/frank89722/Staaaaaaaaaaaack/assets/10683361/0f180ffe-f8fa-4c74-b240-d21a4311ad49

**Comment by frank89722** [comment]
btw I'm using `create-1.19.2-0.5.1.c.jar` with Staaaaack 1.3

**Comment by frank89722** [comment]
fixed in v1.3-56+
Thank you for the report
