### ISSUE TITLE
staaaaaaaaack会让机械动力的石磨失效

### ISSUE THREAD

**Issue by HikariXP** [frank89722/Staaaaaaaaaaaack#11]
**Describe the bug**
引入此mod之后，机械动力的石磨能接收输入物体，但是不能正常工作，

**To Reproduce**
核心应该是create和staaaaaaaack?
Create传送门：https://www.curseforge.com/minecraft/mc-mods/create/files/4835190

**Expected behavior**
可观效果就是吃掉所有输入，零输出
零件在转动，但是不会有任何工作的粒子出现
已经通过JEI确认传入的配方是存在的，比如将小麦磨成小麦粉

**Screenshots**

**Environment**
版本是1.19.2、forge is 43.2.13、create is 0.5.1f、
staaaaaaaaaaaack-forge-1.19.2-0.5.1-20

**Crash log**
Provide a link to a crashlog. E.g. on [Gist](https://gist.github.com/), [pastebin](http://pastebin.com/), or similar.

**Additional context**

**Comment by HikariXP** [comment]
我发了视频在Reddit，有需要可以看一下  
https://www.reddit.com/r/CreateMod/comments/17vo3nf/comment/k9f453u/?context=3

**Comment by frank89722** [comment]
更新 Staaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaack 試試
https://www.curseforge.com/minecraft/mc-mods/staaaaaaaaaaaack/files?page=1&pageSize=20

**Comment by HikariXP** [comment]
你好，更新新的版本是可行的，石磨正常运作，非常感谢你的协助😘
