### ISSUE TITLE
Quantity Display Issue (Maybe not an issue? I'm quite puzzled)

### ISSUE THREAD

**Issue by Oururis** [frank89722/Staaaaaaaaaaaack#13]
I'm sorry for not using the bug report template, as my game isn't crashing and no actual errors are occurring

I'm not sure if this is a bug. I'm playing on version 1.20.4, and it runs fine, but instead of showing the total number of items in a stack, it displays the number of groups. I couldn't find any related settings in the configuration file. Is this something that can be adjusted? I never encountered this while using it in version 1.19.4.

I thought of another possibility. Could it be due to a mod I'm using to optimize game performance that stacks item drops once?

You can clearly see in the screenshot that when I drop a whole bunch of items, sometimes it shows 1 and sometimes it doesn't show anything, and when I drop the 65th item, the number changes to 2
![2024-03-21_02 43 18](https://github.com/frank89722/Staaaaaaaaaaaack/assets/118568742/476138a9-0b9f-4c43-9390-c24c742c8ed7)

Just in case, I used a clean client again, only installing this mod, and the result was consistent.
![2024-03-21_02 51 59](https://github.com/frank89722/Staaaaaaaaaaaack/assets/118568742/340ca72a-4ee6-4c4c-a40f-7b7c4b461711)

**Comment by frank89722** [comment]
This is the new feature in v1.5, and you can modify it in the client configuration.
If you are using fabric, you may need to delete the old config file to get the new setting.

**Comment by Oururis** [comment]
Thank you so much for your response. I did indeed use the old version config directly
