### ISSUE TITLE
Change The Combined Drop

### ISSUE THREAD

**Issue by Junrall** [frank89722/Staaaaaaaaaaaack#15]
I apologize... This is more of a feature request and not really an issue. I'm not sure of where to open feature requests. 

When combining items, set the location of the newly combined items to the spot where the last item was dropped. This allows for strategic control over where the combined items will appear.

Thanks!

**Comment by frank89722** [comment]
I guess I won't add this feature since this mod is made for reduce lag but not change how the game works, sorry :(
