### ISSUE TITLE
Item will display item count when pickup.

### ISSUE THREAD

**Issue by Minecrafthyr** [frank89722/Staaaaaaaaaaaack#3]
Item will display another item count when pickup, but it actually a stack (64 items).

**Comment by frank89722** [comment]
Could you provide a screen record for this?

And this happened in single or multiplayer only?

**Comment by Minecrafthyr** [comment]
Minecraft 1.19.4 fabric v0.4 Singleplayer (with 64 mods)

![2023-06-02_14 51 41](https://github.com/frank89722/Staaaaaaaaaaaack/assets/107340726/ca93309a-0ecb-484a-af0f-8e0ba44d2aa6)

**Comment by Minecrafthyr** [comment]
![2023-06-02_15 10 32](https://github.com/frank89722/Staaaaaaaaaaaack/assets/107340726/e53b2cf8-b3d9-4a28-9c6e-c8febe00d521)
Only with fabric, 1.19.4, Singleplayer

**Comment by Minecrafthyr** [comment]
是的。

**Comment by frank89722** [comment]
已在 v0.5 中改進，感謝你的回報！

![CleanShot 2023-06-03 at 22 49 45](https://github.com/frank89722/Staaaaaaaaaaaack/assets/10683361/abbec3bd-b800-4bba-a4ec-d6fab1020fba)
