### ISSUE TITLE
Allows you to stack unstackable items

### ISSUE THREAD

**Issue by ThatSmartGuy21** [frank89722/Staaaaaaaaaaaack#4]
If you throw multiple unstackable items on the ground, or put them in a chest, when they group up they will stack as an incorrect stack size.

https://github.com/frank89722/Staaaaaaaaaaaack/assets/88632676/0bf23a60-effe-4fb6-9e48-e7e11db1983f

**Comment by frank89722** [comment]
Oh no...

**Comment by ThatSmartGuy21** [comment]
Just now realizing the video didn't work :P woops

**Comment by frank89722** [comment]
Don't worry, the video is working properly for me on a non-Safari browser
and the issue should be fixed in v0.5.1, thank you for your help!
