### ISSUE TITLE
Using some backpack-based mods, items can be acquired indefinitely.

### ISSUE THREAD

**Issue by u7f8au7fbd** [frank89722/Staaaaaaaaaaaack#5]
I am using Mod Ver 1.0 Mc Ver 1.18.2 Forge. I don't know if it is triggered by stacked items being recovered in the player's inventory, but when I use [Sophisticated Backpacks] or other items that put items directly into the backpack instead of the inventory, the count is not reduced and I can acquire stacked items indefinitely.

**Comment by frank89722** [comment]
Thank you for your report! Should be fixed in the latest version

https://modrinth.com/mod/staaaaaaaaaaaack/version/1.18.2-1.0.1-27
