### ISSUE TITLE
/data modify entity @s Item.Count set value 0b is not working properly

### ISSUE THREAD

**Issue by Minecrafthyr** [frank89722/Staaaaaaaaaaaack#6]
## The Bug

Set item count to 0b is not working.  
`StxckExtraItemCount` 1~63: not working properly  
`StxckExtraItemCount` 64+: not working at all

## How to reproduce

`/data modify entity @e[type=minecraft:item,sort=nearest,limit=1] Item.Count set value 0b`

**Comment by frank89722** [comment]
Thank you once again for the bug report! 👊🏿
