### ISSUE TITLE
Conflict with OptiFine shaders

### ISSUE THREAD

**Issue by wsxiya** [frank89722/Staaaaaaaaaaaack#7]
**Describe the bug**
When you use OptiFine to open the shader and enter the game archive, the game will crash. If you enter the archive and then open the shader, the game will not crash. The premise of the game crash is to open the shader and enter the game archive

**To Reproduce**
1. Turn on the shader
2. Enter the game archive
3. 
4. 

**Expected behavior**
Crash when using OptiFine to open the shader and enter the save game

**Screenshots**

**Environment**
- MC version: 1.19.2
- Mod version: OptiFine_I2，staaav1.19.2-1.2-43
- Loader: Forge-43.2.14

**Crash log**
Provide a link to a crashlog. E.g. on [Gist](https://gist.github.com/), [pastebin](http://pastebin.com/), or similar.

**Additional context**

**Comment by frank89722** [comment]
Hi, I need the crash report

**Comment by wsxiya** [comment]
Ok but I'm sure you can easily reproduce this situation

**Comment by wsxiya** [comment]
[错误报告-2023-6-30_12.10.16.zip](https://github.com/frank89722/Staaaaaaaaaaaack/files/11912698/-2023-6-30_12.10.16.zip)

**Comment by frank89722** [comment]
[staaaaaaaaaaaack-forge-1.19.2-1.2-dev.zip](https://github.com/frank89722/Staaaaaaaaaaaack/files/11913401/staaaaaaaaaaaack-forge-1.19.2-1.2-dev.zip)

Can you give this a try? You'll need to rename it from zip to jar

**Comment by wsxiya** [comment]
> [staaa.zip a](https://github.com/frank89722/Staaaaaaaaaaaack/files/11913401/staaaaaaaaaaaack-forge-1.19.2-1.2-dev.zip)
> 
> 你能试一试吗？您需要将其从zip重命名为jar
This is a crash report, not a mod, you can unzip it and have a look at the bug report

**Comment by wsxiya** [comment]
> [staaa.zip a](https://github.com/frank89722/Staaaaaaaaaaaack/files/11913401/staaaaaaaaaaaack-forge-1.19.2-1.2-dev.zip)
> 
> 你能试一试吗？您需要将其从zip重命名为jar
I'll try again, sorry I didn't see clearly just now

**Comment by wsxiya** [comment]
I just tried it and the game still crashes
[错误报告-2023-6-30_14.46.11.zip](https://github.com/frank89722/Staaaaaaaaaaaack/files/11913703/-2023-6-30_14.46.11.zip)

**Comment by frank89722** [comment]
Please report this issue to optifine

**Comment by wsxiya** [comment]
Thanks, this mod is great

**Comment by frank89722** [comment]
Hi, I've added a small patch to prevent the crash in v1.2-50+
But this is still considered an issue in optifine, since when the game has started calling the render entity method they still leave `EntityRenderDispatcher.camera` as null.
